# Generated by Django 5.0 on 2023-12-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensfashion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default='static/default.jpg', upload_to='static/'),
        ),
    ]
