# Generated by Django 5.0 on 2024-01-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensfashion', '0005_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=100)),
            ],
        ),
    ]
