# Generated by Django 5.0 on 2024-01-06 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensfashion', '0010_remove_order_user_order_email_order_first_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phoneno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='phoneno_orders', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
