# Generated by Django 5.0 on 2024-01-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensfashion', '0011_order_phoneno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phoneno',
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
    ]
