# Generated by Django 5.0 on 2024-01-10 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensfashion', '0019_customers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customers',
        ),
    ]
