# Generated by Django 5.0 on 2024-01-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensfashion', '0022_rename_user_order_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='email',
            new_name='user',
        ),
    ]
